# Simple Linear Regression

In [6]:
#import libraries 
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
#read data using pandas
data  = pd.read_csv("https://raw.githubusercontent.com/Avik-Jain/100-Days-Of-ML-Code/master/datasets/studentscores.csv")
data.head()

Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75
4    3.5      30

In [8]:
data.shape

(25, 2)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Hours   25 non-null     float64
 1   Scores  25 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 528.0 bytes


In [10]:
data.isnull().sum()

Hours     0
Scores    0
dtype: int64

In [11]:
#3HOW DATA into dependent and independent values
X = data.iloc[:,:1].values
y = data.iloc[:,1].values

In [12]:
X
#featuere hours

array([[2.5],
       [5.1],
       [3.2],
       [8.5],
       [3.5],
       [1.5],
       [9.2],
       [5.5],
       [8.3],
       [2.7],
       [7.7],
       [5.9],
       [4.5],
       [3.3],
       [1.1],
       [8.9],
       [2.5],
       [1.9],
       [6.1],
       [7.4],
       [2.7],
       [4.8],
       [3.8],
       [6.9],
       [7.8]])

In [13]:
#feature score
y

array([21, 47, 27, 75, 30, 20, 88, 60, 81, 25, 85, 62, 41, 42, 17, 95, 30,
       24, 67, 69, 30, 54, 35, 76, 86], dtype=int64)

In [14]:
#now we have fatures we can split tham

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state =0)

In [17]:
#so we have data split so we can use linear reggression

In [18]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression = regression.fit(X_train,y_train)
#to fit learn reggresin model in training data

In [19]:
#okkks so now we have to predict tha data 

In [20]:
y_pred = regression.predict(X_test)

In [21]:
y_pred

array([16.88414476, 33.73226078, 75.357018  , 26.79480124, 60.49103328])

In [22]:
from sklearn.metrics import classification_report

In [23]:
classification_report(y_y_test)

ValueError: Classification metrics can't handle a mix of continuous and multiclass targets

In [ ]:
#lets have some vizuliazation

In [ ]:
#fittig vizulization for training data
plt.scatter(X_train,y_train,color ="red")
plt.plot(X_train, regression.predict(X_train))

In [ ]:
#for testing data
plt.scatter(X_test,y_test,color ="red")
plt.plot(X_test, regression.predict(X_test))